use std::collections::BTreeSet;
use std::fmt::Write as _;
use std::net::{IpAddr, Ipv4Addr, Ipv6Addr};
use std::path::PathBuf;

use anyhow::{Context, Result};
use sn2_chain::Metagraph;
use tracing::{info, warn};

const TABLE_NAME: &str = "sn2_lightning";

pub async fn emit_nftables(
    netuid: u16,
    network: &str,
    chain_endpoint: Option<&str>,
    axon_port: u16,
    out: Option<PathBuf>,
) -> Result<()> {
    let endpoint = sn2_chain::resolve_endpoint(network, chain_endpoint);
    info!(netuid, %endpoint, "syncing metagraph for firewall ruleset");
    let chain_client = subxt::OnlineClient::<subxt::PolkadotConfig>::from_url(&endpoint)
        .await
        .with_context(|| format!("connecting to subtensor at {endpoint}"))?;
    let mut metagraph = Metagraph::new(netuid);
    metagraph
        .sync(&chain_client)
        .await
        .context("syncing metagraph")?;

    let mut v4: BTreeSet<Ipv4Addr> = BTreeSet::new();
    let mut v6: BTreeSet<Ipv6Addr> = BTreeSet::new();
    let mut skipped = 0usize;
    for n in metagraph.neurons.iter().filter(|n| n.validator_permit) {
        if n.axon_ip.is_empty() {
            skipped += 1;
            continue;
        }
        match n.axon_ip.parse::<IpAddr>() {
            Ok(IpAddr::V4(ip)) => {
                v4.insert(ip);
            }
            Ok(IpAddr::V6(ip)) => {
                v6.insert(ip);
            }
            Err(_) => {
                skipped += 1;
            }
        }
    }
    if skipped > 0 {
        warn!(
            skipped,
            "validator neurons skipped due to missing or unparseable axon IP"
        );
    }

    let ruleset = render_ruleset(axon_port, &v4, &v6);

    match out {
        Some(path) => {
            std::fs::write(&path, ruleset.as_bytes())
                .with_context(|| format!("writing ruleset to {}", path.display()))?;
            info!(
                v4_count = v4.len(),
                v6_count = v6.len(),
                path = %path.display(),
                "wrote nftables ruleset"
            );
        }
        None => {
            print!("{ruleset}");
        }
    }
    Ok(())
}

#[cfg_attr(not(target_os = "linux"), allow(dead_code))]
pub(crate) const NFT_TABLE_NAME: &str = TABLE_NAME;

pub(crate) fn render_ruleset(
    axon_port: u16,
    v4: &BTreeSet<Ipv4Addr>,
    v6: &BTreeSet<Ipv6Addr>,
) -> String {
    let mut s = String::new();
    let _ = writeln!(s, "# Generated by sn2-miner firewall");
    let _ = writeln!(s, "# axon_port = {axon_port}");
    let _ = writeln!(s, "# validator_v4 entries: {}", v4.len());
    let _ = writeln!(s, "# validator_v6 entries: {}", v6.len());
    let _ = writeln!(s);
    let _ = writeln!(s, "add table inet {TABLE_NAME}");
    let _ = writeln!(s, "delete table inet {TABLE_NAME}");
    let _ = writeln!(s, "table inet {TABLE_NAME} {{");
    let _ = writeln!(s, "    set validator_v4 {{");
    let _ = writeln!(s, "        type ipv4_addr");
    let _ = writeln!(s, "        flags interval");
    if !v4.is_empty() {
        let _ = write!(s, "        elements = {{ ");
        let mut first = true;
        for ip in v4 {
            if !first {
                let _ = write!(s, ", ");
            }
            let _ = write!(s, "{ip}");
            first = false;
        }
        let _ = writeln!(s, " }}");
    }
    let _ = writeln!(s, "    }}");
    let _ = writeln!(s, "    set validator_v6 {{");
    let _ = writeln!(s, "        type ipv6_addr");
    let _ = writeln!(s, "        flags interval");
    if !v6.is_empty() {
        let _ = write!(s, "        elements = {{ ");
        let mut first = true;
        for ip in v6 {
            if !first {
                let _ = write!(s, ", ");
            }
            let _ = write!(s, "{ip}");
            first = false;
        }
        let _ = writeln!(s, " }}");
    }
    let _ = writeln!(s, "    }}");
    let _ = writeln!(s, "    chain ingress {{");
    let _ = writeln!(
        s,
        "        type filter hook input priority filter; policy accept;"
    );
    let _ = writeln!(
        s,
        "        udp dport {axon_port} ip saddr @validator_v4 accept"
    );
    let _ = writeln!(
        s,
        "        udp dport {axon_port} ip6 saddr @validator_v6 accept"
    );
    let _ = writeln!(s, "        udp dport {axon_port} drop");
    let _ = writeln!(s, "    }}");
    let _ = writeln!(s, "}}");
    s
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn renders_empty_sets() {
        let ruleset = render_ruleset(8091, &BTreeSet::new(), &BTreeSet::new());
        assert!(ruleset.contains("table inet sn2_lightning"));
        assert!(ruleset.contains("udp dport 8091 drop"));
        assert!(!ruleset.contains("elements"));
    }

    #[test]
    fn renders_populated_v4_set() {
        let mut v4 = BTreeSet::new();
        v4.insert("10.0.0.1".parse().unwrap());
        v4.insert("203.0.113.7".parse().unwrap());
        let ruleset = render_ruleset(8091, &v4, &BTreeSet::new());
        assert!(ruleset.contains("elements = { 10.0.0.1, 203.0.113.7 }"));
        assert!(ruleset.contains("udp dport 8091 ip saddr @validator_v4 accept"));
    }

    #[test]
    fn renders_v6_set_separately() {
        let mut v6 = BTreeSet::new();
        v6.insert("2001:db8::1".parse().unwrap());
        let ruleset = render_ruleset(8091, &BTreeSet::new(), &v6);
        assert!(ruleset.contains("ip6 saddr @validator_v6"));
        assert!(ruleset.contains("2001:db8::1"));
    }
}
